name: Generate Snake  
on:  
  schedule:  
    - cron: "0 0 * * *"  

  workflow_dispatch:  

jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
      - uses: Platane/snk@master  
        id: snake  
        with:  
          github_user_name: paresh954  
          svg_out_path: dist/github-contribution-grid-snake.svg  

      - uses: actions/upload-artifact@v3  
        with:  
          name: snake-animation  
          path: dist/github-contribution-grid-snake.svg  
