name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs once a day at midnight UTC
  workflow_dispatch: # Allow manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: paresh954
          outputs: dist/snake.svg

      - name: Push the generated file
        uses: actions/upload-artifact@v3
        with:
          name: contribution-snake
          path: dist/snake.svg
